<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog" Version="4.4.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.Seq" Version="9.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BiblioGo.Application\BiblioGo.Application.csproj" />
    <ProjectReference Include="..\BiblioGo.Domain\BiblioGo.Domain.csproj" />
    <ProjectReference Include="..\BiblioGo.Infrastructure\BiblioGo.Infrastructure.csproj" />
  </ItemGroup>

</Project>
